version: '3.4'

services:

  server:
    image: edittapi
    container_name: "edittapi"
    environment:
      - ACCESS_KEY=qwe
      - SECRET_KEY=qwe
    build: ./
    command: ./app
    ports:
      - 8000:8000
    depends_on:
      - mongodb
      - localstack

  mongodb:
    image: mongo:latest
    container_name: "mongo"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGODB_DATABASE=editt
    volumes:
      - ./.data/db:/data/db
    ports:
      - 27017:27017
    command: mongod --logpath=/dev/null # --quiet

  localstack:
    image: localstack/localstack:latest
    container_name: "localstack"
    ports:
      - '4563-4599:4563-4599'
      - '8055:8080'
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - './.localstack:/tmp/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'