port: 8000

authorizer:
  username: "edittor"
  password_hash: "b84a6c3adad04a39f4ce1bbb878b5ef28aed4f00"
  signing_key: "wcxhhH0wfG2tuvnXFpo8"
  hash_salt: "0OkSoY3uxtmUxYrDr7Ye"
  token_ttl: 86400

mongo:
  name: "editt"
  publications_collection: "publications"
  metrics_collection: "metrics"

metrics:
  interval: 10 #minutes

# S3 compatible DigitalOcean object storage
storage:
  endpoint: "fra1.digitaloceanspaces.com"
  bucket: "editt-image-storage"